### ISSUE TITLE
Minulé pololetí

### ISSUE THREAD

**Issue by vitkolos** [JosefKuchar/bakalari-api#1]
Jak zobrazím známky z **minulého** pololetí?

**Comment by JosefKuchar** [comment]
Velice se omlouvám za zpoždení, máš namysli konkrétní samostatné známky, nebo co je na vysvědčení?

**Comment by VitKolos** [comment]
Samostatné známky.

**Comment by VitKolos** [comment]
Pmd to asi nebude... Webová aplikace to dělá pomocí dfrom=1709010000&dto=1801310000.

**Comment by JosefKuchar** [comment]
Zajímavé, to asi bude nějaká funkcionalita v nové verzi, protože já takovou možnost vůbec nemám. Tyto parametry mně v url vůbec neovlivňují výsledek. Máš v mobilní aplikaci možnost výběru zobrazení známek z daného pololetí?

**Comment by VitKolos** [comment]
Právě, že ne. Kdyby jo, neměli bychom se o čem bavit. :D

**Comment by JosefKuchar** [comment]
A ta nová "beta aplikace" ti funguje?

**Comment by JosefKuchar** [comment]
Asi ti nezbude nic jiného, než naparsovat webovou aplikaci, ale předem varuju, že je to docela prasárna

**Comment by VitKolos** [comment]
Beta aplikace? To mi nějak uniklo... :) Jestli najdeš, kde bych ji mohl stáhnout, napiš.

Ta funkcionalita pro mě není moc důležitá, takže se bez ní odejdu a web nebudu parsovat (ani nevím, jak bych to dělal).

**Comment by JosefKuchar** [comment]
Všechno nasvědčuje tomu, že mobilní a webová aplikace má jiný backend, takže se člověk k některým věcem snadno nedostane :/

**Comment by vitkolos** [comment]
Ono je hlavně tak trochu to API pro mobilní aplikaci takový další frontend, který neposkytuje víc, než je třeba. 😄

**Comment by JosefKuchar** [comment]
Mě přijde docela kompletní, nevím jak je to u té učitelské části... Každopádně na začátku roku jsem měl rozvrh v aplikaci mnohem dřív než na webu, takže je to nějak kompletně oddělené

**Comment by JosefKuchar** [comment]
Můžeš ještě zeditovat to README.md jak ti píšu v tom PR? Normálně to uprav a pushni to do masteru :)

**Comment by vitkolos** [comment]
Teď se nedostanu k počítači, v pondělí se na to vrhnu. 😉
