### ISSUE TITLE
Další parametry

### ISSUE THREAD

**Issue by vitkolos** [JosefKuchar/bakalari-api#11]
Proč je u všech položek nadpis „Další parametry“ (nebo „Parametry“), i když pod ním nic není? Je tam nezbytný? 😃

**Comment by JosefKuchar** [comment]
Měl jsem pocit, že nějaké budou. Nejspíš jsem se šeredně mýlil...

**Comment by vitkolos** [comment]
Mám ty nadpisy všude zrušit, nebo s nimi něco plánuješ? 😃

**Comment by JosefKuchar** [comment]
Kde nic není tak můžeš, například u rozvrhu je parametr pmd

**Comment by vitkolos** [comment]
Jo, mám na mysli samozřejmě pouze ty prázdné :D

**Comment by JosefKuchar** [comment]
#14
