### ISSUE TITLE
JSON request na domovské sránce

### ISSUE THREAD

**Issue by mariansam** [JosefKuchar/bakalari-api#18]
Když se v mobilní aplikaci otevře domovská stránka, aplikace musí získat nové zprávy, nové známky a nové úkoly. Dělá to pomocí tohoto JSON requestu.
**Req:**
```
POST /if/2/overview/notifications HTTP/1.1
Accept: application/json
Authorization: Basic QU5EUjpEUHdfUHE2TEhqVEJIc3BqMUVkcEJVb3hVZF9kaVljdVBtWDZraFJ4S0NSLThoTC0xR0VGODhtM2VrUjJJeFhFMVZ0YU9jQTNMRW5BV0JwM2N6OGV4UT09
Content-Length: 158
Content-Type: application/json
Host: bakalari.gjp-me.cz
Connection: Keep-Alive
User-Agent: Apache-HttpClient/UNAVAILABLE (java 1.5)
Accept-Encoding: gzip,deflate
```
```json
{
        "classificationFrom": "20180910",
        "classificationTo": "20180911", 
        "homeworksFrom": "20180909",
        "homeworksTo": "20180911",
        "MessageType": "Overview.Notifications.Req"
}
```
**Res:**
```
HTTP/1.1 200 OK
Cache-Control: private
Content-Type: application/json
Server: Microsoft-IIS/7.5
Set-Cookie: ASP.NET_SessionId=wduycrbprc211baxk04lyokt; path=/; HttpOnly
X-AspNet-Version: 4.0.30319
Set-Cookie: ASP.NET_SessionId=wduycrbprc211baxk04lyokt; path=/; HttpOnly
Set-Cookie: BakaSession=04d0d5c0-b3e8-4a3e-bda2-337b5a3c12bd; expires=Tue, 11-Sep-2018 17:37:42 GMT; path=/; HttpOnly
X-Powered-By: ASP.NET
Date: Tue, 11 Sep 2018 17:22:42 GMT
Content-Length: 112
```
```json
{
        "KomensMessagesCount": 0,
        "HomeworksCount": 0,
        "ClassificationCount": 0,
        "MessageType": "Overview.Notifications.Resp"
}
```
Nechápu proč je to najednou JSON. Nerozumím cestě (`/if/2/overview/notifications`). Nechápu autorizaci (token v `Authorization` se liší). Vy tomu rozumíte?
PS. není slovo _homework_ v angličtině nepočitatelné?

**Comment by vitkolos** [comment]
Rozumím tomu, interface 2 používá místo XML JSON, všechno funguje trochu jinak (a asi moderněji?). Podrobnosti pošlu později.

**Comment by vitkolos** [comment]
Cestě taky nerozumím, homework je opravdu nepočitatelné 😃, autorizace probíhá pomocí normálního tokenu (s datem), jen se před něj přidá `ANDR:` a celé se to zakóduje Base 64 (akorát je potom v té hlavičce  ještě navíc slovo Basic).
Asi jsi to tak myslel, ale pro jistotu doplním, že to nezískává nové známky, zprávy a úkoly, ale pouze jejich počet. 😉

**Comment by mariansam** [comment]
Super, díky. Furt nerozumím tomu, jak to zjišťujete? Vždyť zjistit, že to je normální token + `ANDR` musí být strašně složitý, ne? A taky jak @JosefKuchar zjistil generování tokenu, vždyť to skoro nejde, ne?

**Comment by vitkolos** [comment]
Máme svoje metody. 😎 
Nutno podotknout, že jsme na generování tokenu přišli nezávisle na sobě oba, ačkoli já asi o dost bolestnější cestou. 😄

**Comment by mariansam** [comment]
Ne. Vše jsi mi vysvětlil. Díky. Zavírám. 
(Je to poprvý, co zavírám issue, chci si to užít :D)
