### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by mariansam** [JosefKuchar/bakalari-api#2]
Ahoj,

dokumentace je krásná, sice jsem na vytvářením tokenu strávil asi dvě hodiny, protože se mi tam občas dostal `\n`, ale už to funguje.

Chtěl bych se zeptat, jakým způsobem se dá podílet na vývoji. Protože moc nejde udělat Pull Request do Wiki.

**Comment by JosefKuchar** [comment]
To mně při vývoji úplně nedošlo... až se k tomu dostanu, tak to přemigruju na markdown soubory přímo do repozitáře

**Comment by JosefKuchar** [comment]
Tak jo, hotovo. Jakýkoli užitečný PR vítám

**Comment by mariansam** [comment]
Juu, díky. Mezitím jsem v Pythonu dělal token generator (btw. Python vůbec neumím) - https://github.com/mariansam/bakalari-token-generator
Bylo by super, kdyby tu na to byl odkaz.
Jinak jak zjišťuješ parametry k modulům? Chtěl jsem vyzkoumat Výuku. Po requestu na modul Výuka jsem dostal
```xml
<error>
  <code>105</code>
  <message>interni chyba: Klíč nemůže mít hodnotu NULL.
Název parametru: key</message>
  <result>01</result>
</error>
```

**Comment by JosefKuchar** [comment]
Sniffuju traffic z oficiální aplikace bakalářů na android pomocí https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture
