### ISSUE TITLE
Získání rozvrhu na další den

### ISSUE THREAD

**Issue by Tadeas-grohmi** [JosefKuchar/bakalari-api#57]
Nemůžu se dostat k rozvrhu na další den, request má formát: 'https://bakalari.mojeskola.cz/api/3/timetable/actual?date=2022-11-15'
Dnes je 14, pokud zadám do requestu jakýkoliv den předtím tak to normálně funguje, pokud ale zadám zítřek atd, tak to stále vypisuje dnešek. Je to chyba u mě?

**Comment by Lastaapps** [comment]
Ahoj, soudě podle uzavřené issue v aktuálním repu soudím, že jsi problém vyřešil Jinak ale tohle chování je správné - endpoint si vezme nejbližší pondělí a pro něj vrátí rozvrh na celý týden. Teda pokud to nějak za ty 2 roky výrazně nepřekopali, to by se ale počítám někdo ozval s issue počítám.

**Comment by Tadeas-grohmi** [comment]
Jooo je to tak, přehlédl jsem že to je pro celý týden, měl jsem za to, že to vrací pouze jeden den. Ale i tak děkuji za odpověď.
